# Generated by Django 4.2.5 on 2024-06-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remetente_email', models.CharField(default='null', max_length=200)),
                ('destinatario_email', models.CharField(default='null', max_length=200)),
                ('descricao', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
