# Generated by Django 4.2.5 on 2024-06-02 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='usuario',
        ),
    ]
