# Generated by Django 4.2.5 on 2024-06-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_remove_livro_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='genero',
            field=models.CharField(choices=[('fiction', 'Ficção'), ('non-fiction', 'Não Ficção'), ('romance', 'Romance'), ('mystery', 'Mistério')], default='fiction', max_length=20),
        ),
        migrations.AddField(
            model_name='livro',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='livros/'),
        ),
    ]
