# Generated by Django 4.2.5 on 2024-06-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0003_livro_genero_livro_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='data_publicacao',
        ),
    ]
