# Generated by Django 4.2.5 on 2024-06-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0004_remove_livro_data_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='ano_publicacao',
            field=models.IntegerField(default=2024),
        ),
    ]
