# Generated by Django 4.2.5 on 2024-06-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0005_livro_ano_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='usuario',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
