# Generated by Django 4.2.5 on 2024-05-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cep',
            field=models.CharField(default=0, max_length=9, verbose_name='CEP'),
            preserve_default=False,
        ),
    ]
