# Generated by Django 4.2.5 on 2024-06-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designa se este usuário pode acessar a área de administração.', verbose_name='Membro da equipe'),
        ),
    ]
