# Generated by Django 4.2.5 on 2024-06-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0006_alter_usuario_nome"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="foto_perfil",
            field=models.ImageField(
                blank=True,
                default="media/profile-pic.jpg",
                null=True,
                upload_to="perfil_fotos/",
            ),
        ),
    ]
